[package]
name = "colink-protocol-policy-module"
version = "0.1.5"
edition = "2021"

[dependencies]
colink = "0.3.3"
prost = "0.10"
regex = "1.5"
tokio = "1.24"
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
prost-build = "0.10"
