[package]
name = "policy_module"
version = "0.1.2"
keywords = ["policy module", "colink internal"]
description = "The internal CoLink module for customizable policy checking of protocol execution"
entrypoint = "cargo run"

[policy_module]
name = "policy_module"
description = "policy module"
