[package]
name = "policy_module"
version = "0.1.1"
keywords = ["policy module"]
description = "policy module"
entrypoint = "cargo run"

[policy_module]
name = "policy_module"
description = "policy module"
